### ISSUE TITLE
解包至Checkpoint的阶段发生报错

### ISSUE THREAD

**Issue by ChichiMomo** [wtdcode/CelesteExtractor#2]
![BD$_T8GNL%Z349 P$RYV_BR](https://user-images.githubusercontent.com/61577364/75520206-f2baf680-5a3f-11ea-8503-59f3860d3bdc.png)

**Comment by wtdcode** [comment]
Celeste某个版本后目前本工具有点小问题。。。拆好的资源我在贴吧也发过一份。

**Comment by noiob** [comment]
Here's the same error in English
![grafik](https://user-images.githubusercontent.com/8197071/92417198-4d58ac00-f161-11ea-8025-c304539f593c.png)

**Comment by wtdcode** [comment]
@noiob Thanks for your report. I have known that the tool has some problems with the latest Celeste. I will fix it as soon as possible these days.

**Comment by wtdcode** [comment]
@ChichiMomo @noiob 
Try the new release: https://github.com/wtdcode/CelesteExtractor/releases/tag/v1.1.

**Comment by noiob** [comment]
That works perfectly! Thanks a lot!
